# Generated by Django 5.1.4 on 2024-12-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
